import streamlit as st

st.title("Betty the future conqueror of Gazorpazorpia")
if st.button("click me"):
    st.write("Also bbg, finde das Lied heraus?!.")
    st.write("1, 2, 3, 4, 5, 6, 7, 8, 9, aus")
    st.write("Alle warten auf das Licht")
    st.write("Fürchtet euch, fürchtet euch nicht")
    st.write("Die Sonne scheint mir aus den Augen")
    st.write("Sie wird heut Nacht nicht untergeh'n")
    st.write("Und die Welt zählt laut bis zehn Eins, hier kommt die Sonne")
    st.write("Zwei, hier kommt die Sonne")
    st.write("Drei, sie ist der hellste Stern von allen")
    st.write("Vier, hier kommt die SonneDie Sonne scheint mir aus den Händen")
    st.write("Kann verbrennen, kann euch blenden")
    st.write("Wenn sie aus den Fäusten bricht")
    st.write("Legt sich heiß auf das Gesicht")
    st.write("Sie wird heut Nacht nicht untergeh'n")
    st.write("Und die Welt zählt laut bis zehn")
    st.write("Eins, hier kommt die Sonne")
    st.write("Zwei, hier kommt die Sonne")
    st.write("Drei, sie ist der hellste Stern von allen")
    st.write("Vier, hier kommt die SonneFünf, hier kommt die Sonne")
    st.write("Sechs, hier kommt die Sonne")
    st.write("Sieben, sie ist der hellste Stern von allen")
    st.write("Acht, neun, hier kommt die Sonne Die Sonne scheint mir aus den Händen")
    st.write("Kann verbrennen, kann dich blenden")
    st.write("Wenn sie aus den Fäusten bricht")
    st.write("Legt sich heiß auf dein Gesicht")
    st.write("Legt sich schmerzend auf die Brust")
    st.write("Das Gleichgewicht wird zum Verlus")
    st.write("Lässt dich hart zu Boden geh'n")
    st.write("Und die Welt zählt laut bis zehn")
    st.write("Eins, hier kommt die Sonne")
    st.write("Zwei, hier kommt die Sonne")
    st.write("Drei, sie ist der hellste Stern von allen")
    st.write("Vier, und wird nie vom Himmel fallen")
    st.write("Fünf, hier kommt die Sonne")
    st.write("Sechs, hier kommt die Sonne")
    st.write("Sieben, sie ist der hellste Stern von allen")
    st.write("Acht, neun, hier kommt die Sonne")
    st.write("guess this other song")
    st.write("Es war einmal in einem kleinen Städtchen, da")
    st.write("Lebte ein Mädchen namens Barbara")
    st.write("Und diese Barbara war im ganzen Land")
    st.write("Für ihren abartig guten Rhabarberkuchen bekannt")
    st.write("Ja, man konnte sagen, dass Barbaras")
    st.write("Rhabarberkuchen ohne Wenn und Aber gar")
    st.write("Eine grade zu magische Erfahrung war")
    st.write("Aberakadabera")
    st.write("Tja, dieser Kuchen war grade zu bombastisch")
    st.write("Und die Nachfrage danach erstarke drastisch")
    st.write("Barbara eröffnete noch im selben Jahr")
    st.write("Eine Bar und nannte sie Barbaras Rhabarberbar")
    st.write("In der Stadt gab es auch ein paar Barbaren")
    st.write("")

