import streamlit as st

st.title("Beta Scythe, Delta Sword, and TideSea Dagger: THE BREAKDOWN ORIGIN")
st. text ("A long time ago, the most powerful glitches were created.")
st. text ( "One was allied along the dead, descendant of Death, called Beta Scythe." ) 
st. text ( "One was allied with humans, offspring of humanity, named Delta sword." )
st. text ( "One was allied with either race, child of The Cosmos, TideSea Dagger." )
st. text ( "Every one was part of one club, called the Dynamitronics.")
st. text ( "Beta Scythe, Delta Sword, and TideSea Dagger were clearly the elite ones in their group.")
st.title ( "UNTIL ONE DAY..." )
st. text ( "The leaders of each group shut down each Dynamitronic." )
st. text ( "Or, really, each that they KNEW of.")
st. text ("There was still one Dynamitronic left.")
st. text ( "His name was Pi Knife, the remains of sorrow, the fourth Dynamitronic.")
st. text ("He got along well with the other Dynamitronics.")
st. text ("He knew that Beta Scythe, Delta Sword, and TideSea Dagger were in trouble.")
st. text ( "He first activated Beta Scythe. Beta Scythe was grateful to see Pi Knife again after their last adventure of the Mountains of Tyhsoni.")
st. text ( "Then, with the help of Beta Scythe, Pi Knife freed Delta Sword from isolation. Delta Sword was also grateful to see Pi Knife after the Mountains of Thysoni.")
st. text ( "Then, with Beta Scythe and Delta Sword, Pi Knife broke off the chains of misdirection from TideSea Dagger. TideSea Dagger was also glad to see Pi Knife after the Mountains of Thysoni.")
st. text ( "Then, the Dynamitronics went back to each of their groups, and Pi Knife went with TideSea Dagger. If anybody bothered them, the Dynamitronics would be ready to fight.")
st.title ( "THE END")